"""empty message

Revision ID: 92775e8741f0
Revises: d68c9c6f3dcc
Create Date: 2019-08-07 15:55:24.278604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92775e8741f0'
down_revision = 'd68c9c6f3dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('lines', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabs')
    # ### end Alembic commands ###
